### ISSUE TITLE
No need of an else just write the return after the if will work.

### ISSUE THREAD

**Issue by ankitjain28may** [ncs-jss/Proj_mx02#66]
https://github.com/ncs-jss/Proj_mx02/blob/ed2b4a6a6ebf84060c162932da32c2108212b77d/app/Http/Controllers/EventPlayController.php#L84

**Comment by anantjain6** [comment]
In #78 I had return back with a proper error message.

**Comment by anantjain6** [comment]
Sorry, it looks like I forgot to push the code
