### ISSUE TITLE
Check this properly

### ISSUE THREAD

**Issue by ankitjain28may** [ncs-jss/Proj_mx02#67]
Didn't try but.. if this is 4th event and your question queue has questions with id- 82,83,84 but the count will be still 3 so it will not allow the user to play. Recheck it

https://github.com/ncs-jss/Proj_mx02/blob/ed2b4a6a6ebf84060c162932da32c2108212b77d/app/Http/Controllers/EventPlayController.php#L104

**Comment by anantjain6** [comment]
Sir, this validation is for number of questions
Example if there are 3 questions in an event
Then user can't open domain.com/event/play/4

**Comment by ankitjain28may** [comment]
What is `$queid` here ?

**Comment by anantjain6** [comment]
The question ID from route

**Comment by ankitjain28may** [comment]
is it equal to the `id` column of `question` table ?

**Comment by anantjain6** [comment]
No sir, its in the pattern 1, 2, 3,4 ... n number of question for that event

**Comment by ankitjain28may** [comment]
Okay, then its fine, Closing this.
