### ISSUE TITLE
don't do many changes in one PR

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/Proj_mx02#9]
@anantjain6 I saw https://github.com/ncs-jss/Proj_mx02/pull/8/files and one feedback I can give is to not add many features in one PR or change so many files. Keep PR small and manageable

**Comment by anantjain6** [comment]
Sir, actually me & Rohit are working on it and as I give PR then he can push from master and start working on his branch. hence, unfortunately, we are unable to make PR small

**Comment by itaditya** [comment]
@anantjain6 make multiple PRs then.

**Comment by anantjain6** [comment]
ok sir, i'll
